name: flutter_study
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # flutter fluro
  fluro: "^1.4.0"

  # flutter dio
  dio: ^1.0.9

  # rxdart
  rxdart: ^0.18.1

  # flutter flutter_swiper
  flutter_swiper: ^1.1.4

  # 本地轻量存储
  shared_preferences: ^0.5.0

  #时间格式化处理库
  intl: ^0.15.7

  #加载html
  flutter_html: ^0.8.2

  #视频组件
  video_player: ^0.9.0

  #快速生成App的launcherIcon
  flutter_launcher_icons: "^0.7.0"

  #获取设备信息
  device_info: ^0.4.0+1

  # 下拉刷新、上拉加载组件
  pull_to_refresh: ^1.2.0

  # 时间选择器
  flutter_datetime_picker: ^1.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/app_launcher_icon/launcher.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/order/books.jpg
   - assets/images/common/avatar.jpeg
   - assets/images/common/placeholder.png
   - assets/images/commodity_detail/like-icon.png
   - assets/images/commodity_detail/share.png
   - assets/images/commodity_detail/arrow-right-red.png
   - assets/images/commodity_detail/menu-icon.png
   - assets/images/splash_screen/splash.jpg
   - assets/images/splash_screen/splash@2x.jpg
   # 国际化语言包
   - assets/locale/i18n_en.json
   - assets/locale/i18n_zh.json
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Lora
      fonts:
       - asset: assets/fonts/Lora-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
